### ISSUE TITLE
How to execute the parser?

### ISSUE THREAD

**Issue by NAK3DDesigns** [Berranzan/Belt-Parser#1]
Hello,
I've been using the Blackbelt Cura for my White Knight belt printer I designed.  Unfortunately their version does not seem to be compatible with REPRAP based printers and I'm having extrusion issues.  I was hoping to try your parser but am having issues getting it to work.  How do I execute the program?

Thanks
Karl Brown
NAK3D Designs

**Comment by NAK3DDesigns** [comment]
ok, so I think I managed to get it built with VS though I'm no programmer..  Issue I'm seeing in the gcode is that its starting the Y-axis height at .001.  Is there a way to create an offset to dial in bed clearance or can you tell me what setting in cura will change that height?

**Comment by Berranzan** [comment]
It has been a while since I touched this program, the best description of how it works is in Read Me.pdf file. It simply takes Cura code and applies Y axis correction so it lays on the bed. Just enter your angle that you used in Cura in Angle textbox and click Apply calculated angle, then click Parse.

> _As to why it starts at .001 it has to do with your layer height in Cura._  _There should be no need to change this in parser as it just follows what the Cura has generated, and again for emphasis, it just acts upon Y value generated in Cura, it does not add or remove layers._ 

 - disregard this.

I didn't realize that Github didn't include executable file and I apologize for that.

**Comment by Berranzan** [comment]
I suggest as a last resort that you open Cura file and Parser file in a text editor and compare lines side by side to see what has been changed and if anything change it manually to whatever value you think it may help, in your case to Y = 0.
I did mangle in my previous reply what is going on with Y layer, as Cura will generate Z layers according to layer thickness and not the Y layer. Y is calculated in the Parser to be as close as possible to zero for layers that suppose to be on the bed, and higher for layers that are not. It is not exact because Cura has approximations and rounding that is inherent, and you can try to fix that by clicking on Recalculate Optimal angle.

**Comment by Berranzan** [comment]
To elaborate bit more, Parser will start from the layers that in Cura appear to be farthest along the virtual Z axis (see pdf file) and try to "zero" them where appropriate because the deviation will be the worst there for any Cura angle rounding, and then calculate offsets back to Z=0 where the deviation should be minimal.

**Comment by NAK3DDesigns** [comment]
Ok, I think you are actually confusing me more.  Lol.  So far I’ve tried changing the actual position of the model to .4 above the bed= no change.    If changed initial layer height from .2 to .4 = no change.   I can’t seem to find the setting to make go above Y-axis .001 as a starting point.

**Comment by Berranzan** [comment]
I think that your printer axis configuration is different from the one I have developed parser for, as Y and Z in parser are flipped, Z being the axis along the belt and Y basically what it used to be Z axis. That is why Y is always close to zero at first layer.
Please refer to Read Me .pdf file to confirm if your axis orientation is the same as pictured.

**Comment by NAK3DDesigns** [comment]
No, mine is set up the same way.   I completely understand that Y and Z are flipped, my problem is getting it to change the thickness of the belt layer.   I don’t want the section of each layer closest to the belt to be a .001.  That is too close and the hotend would damage the belt.   I need it to be closer to .2 to .4.

**Comment by NAK3DDesigns** [comment]
Maybe this would be quicker if we did a google hangout.    You can email me direct at NAK3DDesigns@gmail.com

**Comment by Berranzan** [comment]
Ah OK, well Parser will try to put it as close to zero as possible, I can add an option to add offset eventually but for now I suggest you adjust your printer bed leveling to offset for it, IE make bed zero level to be offset necessary amount.

**Comment by NAK3DDesigns** [comment]
Thanks that would be great.    That isn’t quite as simple with my design, but I’ll give it a shot.
